global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    bot: 'go-crypto-bot'

scrape_configs:
  - job_name: 'writer'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['writer:9101']
        labels:
          binary: 'writer'

  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']
