




parameters:
    sentiment_rss:



        - https://rss.app/feeds/VXziG7PJ674f9i8I.xml
        - https://insidebitcoins.com/feed
        - https://investing.com/rss/news_301.rss
        - https://www.coindesk.com/arc/outboundfeeds/rss/
        - https://bitcoinist.com/feed/
        - https://www.newsbtc.com/feed/

services:

    _defaults:
        autowire: true
        autoconfigure: true

    Bundles\CryptoBotContext\:
        resource: '../../../CryptoBotContext/'
        exclude:
            - '../../Entity/'
            - '../../Model/'
            - '../../Event/'
            - '../../Exception/'
            - '../../CryptoBotContextBundle.php'

    Bundles\CryptoBotContext\EntitySubscriber\:
        resource: '../../EntitySubscriber'
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Bundles\CryptoBotContext\Service\RSSParser:
        arguments:
            $rssFeeds: '%sentiment_rss%'
