# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    sentiment_rss:
        #- https://bitcoinmagazine.com/.rss/full/ - 403
        #- https://cointelegraph.com/rss - 403
        #- https://bitpay.com/blog/rss/
        - https://rss.app/feeds/VXziG7PJ674f9i8I.xml # Elon Mask Twitter
        - https://insidebitcoins.com/feed
        - https://investing.com/rss/news_301.rss
        - https://www.coindesk.com/arc/outboundfeeds/rss/
        - https://bitcoinist.com/feed/
        - https://www.newsbtc.com/feed/

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Bundles\CryptoBotContext\:
        resource: '../../../CryptoBotContext/'
        exclude:
            - '../../Entity/'
            - '../../Model/'
            - '../../Event/'
            - '../../Exception/'
            - '../../CryptoBotContextBundle.php'

    Bundles\CryptoBotContext\EntitySubscriber\:
        resource: '../../EntitySubscriber'
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Bundles\CryptoBotContext\Service\RSSParser:
        arguments:
            $rssFeeds: '%sentiment_rss%'

    Bundles\CryptoBotContext\Service\SentimentService:
        arguments:
            $env: '%kernel.environment%'
