doctrine:
  orm:
    mappings:
      TgBotContext:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/bundles/TgBotContext/Entity'
        prefix: 'Bundles\TgBotContextBundle\Entity'
        alias: TgBotContext
