doctrine:
  orm:
    mappings:
      CryptoBotContext:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/bundles/CryptoBotContext/Entity'
        prefix: 'Bundles\CryptoBotContextBundle\Entity'
        alias: CryptoBotContext
