services:
    frontend:
        build:
            context: .
            args:
                API_BASE_URL: "${API_BASE_URL:-http://localhost:81}"
                CLIENT_ID: "${CLIENT_ID:-}"
                CLIENT_SECRET: "${CLIENT_SECRET:-}"
        environment:
            HOST: 0.0.0.0
            PORT: 3000
            NODE_ENV: development
        ports:
            - "3000:3000"
        volumes:
            - .:/home/node/app
            - /home/node/app/node_modules
            - /home/node/app/.nuxt
            - /home/node/app/.output
        command: yarn dev
        restart: on-failure
        networks:
            - crypto-saas-ui

networks:
    crypto-saas-ui:
        driver: bridge
