# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    test.queue_serializer: '@messenger.transport.jms_serializer'

    test.message.bus: '@messenger.bus.default'

    test.client_interface: '@GuzzleHttp\ClientInterface'

    test.brute_force_security: '@Bundles\UserContext\Service\BruteForceSecurity'

    test.tg_message_builder: '@Bundles\TgBotContext\MessageBuilder'

    test.cryptobot_service: '@Bundles\CryptoBotContext\Service\CryptoBotService'

    test.cached_trade_list_interface: '@Bundles\CryptoBotContext\Service\CachedTradeListServiceInterface'

    test.email_sender: '@Bundles\UserContext\Service\EmailSender'

    test.trade_repository: '@Bundles\CryptoBotContext\Repository\TradeRepository'

    test.trade_registry: '@Bundles\CryptoBotContext\Service\TradeRegistry'
