




parameters:
    locale: en

services:

    _defaults:
        autowire: true
        autoconfigure: true



    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Knp\Component\Pager\PaginatorInterface: '@knp_paginator'

    App\Service\UserProviderDecorator:
        decorates: Symfony\Component\Security\Core\User\UserProviderInterface
        arguments:
            $userProvider: '@.inner'

    GuzzleHttp\Client:
        arguments:
            - timeout: 60
            - connect_timeout: 60
            - verify: false

    GuzzleHttp\ClientInterface: '@GuzzleHttp\Client'

    App\Controller\PublicRoute\RegistrationController:
        arguments:
            $environment: '%kernel.environment%'

    App\EventListener\ExceptionListener:
        tags:
            - { name: 'kernel.event_listener', event: 'messenger.message_failed', method: 'onMessageFailed', priority: 255 }

    App\Controller\PublicRoute\InternalController:
        arguments:
            $internalToken: '%env(INTERNAL_SERVICE_TOKEN)%'
