




parameters:
    locale: 'en'

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    test.queue_serializer: '@messenger.transport.jms_serializer'

    test.message.bus: '@messenger.bus.default'

    test.client_interface: '@GuzzleHttp\ClientInterface'

    test.brute_force_security: '@Bundles\UserContext\Service\BruteForceSecurity'

    test.tg_message_builder: '@Bundles\TgBotContext\MessageBuilder'

    test.cryptobot_service: '@Bundles\CryptoBotContext\Service\CryptoBotService'

    test.cached_trade_list_interface: '@Bundles\CryptoBotContext\Service\CachedTradeListServiceInterface'

    test.email_sender: '@Bundles\UserContext\Service\EmailSender'

    test.trade_repository: '@Bundles\CryptoBotContext\Repository\TradeRepository'

    test.trade_registry: '@Bundles\CryptoBotContext\Service\TradeRegistry'
