<?php

$header = 'This file is private property of the author, keep it secure and do not share anywhere out of the author.';

$finder = (new PhpCsFixer\Finder())
    ->in([__DIR__ . '/src', __DIR__ . '/tests', __DIR__ . '/bundles']);
;

return (new PhpCsFixer\Config())
    ->setRules([
        '@Symfony' => true,
        'no_superfluous_phpdoc_tags'                  => false,
        '@PSR1'                                       => true,
        '@PSR2'                                       => true,
        '@DoctrineAnnotation'                         => true,
        'align_multiline_comment'                     => [
            'comment_type' => 'all_multiline',
        ],
        'array_syntax'                                => [
            'syntax' => 'short',
        ],
        'backtick_to_shell_exec'                      => true,
        'binary_operator_spaces'                      => [
            'default' => 'align_single_space',
        ],
        'blank_line_before_statement'                 => [
            'statements' => ['return', 'try'],
        ],
        'cast_spaces'                                 => true,
        'class_attributes_separation'                 => true,
        'combine_consecutive_issets'                  => true,
        'combine_consecutive_unsets'                  => true,
        'concat_space'                                => [
            'spacing' => 'one',
        ],
        'escape_implicit_backslashes'                 => true,
        'explicit_string_variable'                    => true,
        'function_to_constant'                        => true,
        'function_typehint_space'                     => true,
        'include'                                     => true,
        'increment_style'                             => true,
        'is_null'                                     => true,
        'lowercase_cast'                              => true,
        'mb_str_functions'                            => true,
        'modernize_types_casting'                     => true,
        'multiline_comment_opening_closing'           => true,
        'native_function_casing'                      => true,
        'native_function_invocation'                  => true,
        'new_with_braces'                             => true,
        'no_alias_functions'                          => true,
        'no_blank_lines_after_class_opening'          => true,
        'no_blank_lines_after_phpdoc'                 => true,
        'single_blank_line_before_namespace'          => true,
        'no_empty_comment'                            => true,
        'no_empty_phpdoc'                             => true,
        'no_empty_statement'                          => true,
        'no_extra_blank_lines'                        => true,
        'no_homoglyph_names'                          => true,
        'no_leading_import_slash'                     => true,
        'no_leading_namespace_whitespace'             => true,
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_null_property_initialization'             => true,
        'no_php4_constructor'                         => true,
        'no_short_bool_cast'                          => true,
        'no_singleline_whitespace_before_semicolons'  => true,
        'no_spaces_around_offset'                     => true,
        'no_superfluous_elseif'                       => true,
        'no_trailing_comma_in_list_call'              => true,
        'no_trailing_comma_in_singleline_array'       => true,
        'no_unneeded_control_parentheses'             => true,
        'no_unneeded_curly_braces'                    => true,
        'no_unneeded_final_method'                    => true,
        'no_unreachable_default_argument_value'       => true,
        'no_unused_imports'                           => true,
        'no_useless_else'                             => true,
        'no_useless_return'                           => true,
        'no_whitespace_before_comma_in_array'         => true,
        'no_whitespace_in_blank_line'                 => true,
        'non_printable_character'                     => [
            'use_escape_sequences_in_strings' => true,
        ],
        'normalize_index_brace'                       => true,
        'object_operator_without_whitespace'          => true,
        'ordered_imports'                             => true,
        'php_unit_construct'                          => true,
        'php_unit_dedicate_assert'                    => true,
        'php_unit_expectation'                        => true,
        'php_unit_fqcn_annotation'                    => true,
        'php_unit_mock'                               => true,
        'php_unit_namespaced'                         => true,
        'phpdoc_add_missing_param_annotation'         => true,
        'phpdoc_align'                                => true,
        'phpdoc_annotation_without_dot'               => true,
        'phpdoc_indent'                               => true,
        'phpdoc_no_alias_tag'                         => true,
        'phpdoc_no_empty_return'                      => true,
        'phpdoc_no_package'                           => true,
        'phpdoc_no_useless_inheritdoc'                => true,
        'phpdoc_order'                                => true,
        'phpdoc_return_self_reference'                => true,
        'phpdoc_scalar'                               => true,
        'phpdoc_separation'                           => true,
        'phpdoc_single_line_var_spacing'              => true,
        'phpdoc_summary'                              => true,
        'phpdoc_to_comment'                           => true,
        'phpdoc_trim'                                 => true,
        'phpdoc_types'                                => true,
        'phpdoc_types_order'                          => true,
        'phpdoc_var_without_name'                     => true,
        'pow_to_exponentiation'                       => true,
        'protected_to_private'                        => true,
        'random_api_migration'                        => true,
        'return_type_declaration'                     => true,
        'self_accessor'                               => true,
        'semicolon_after_instruction'                 => true,
        'short_scalar_cast'                           => true,
        'single_line_comment_style'                   => true,
        'single_quote'                                => true,
        'space_after_semicolon'                       => true,
        'standardize_not_equals'                      => true,
        'strict_comparison'                           => true,
        'strict_param'                                => true,
        'ternary_operator_spaces'                     => true,
        'ternary_to_null_coalescing'                  => true,
        'trailing_comma_in_multiline'                 => true,
        'trim_array_spaces'                           => true,
        'unary_operator_spaces'                       => true,
        'whitespace_after_comma_in_array'             => true,
        'yoda_style'                                  => true,
        'header_comment'                              => [
            'header'       => $header,
            'comment_type' => 'PHPDoc',
            'separate'     => 'bottom',
        ],
    ])
    ->setFinder($finder)
;
