services:
    backend:
      build:
        context: '.'
        args:
            UID: $UID
            GID: $GID
      environment:
          UID: $UID
          GID: $GID
          APP_ENV: 'dev'
          DEPLOY_SERVICE_IP: 'host.docker.internal'
          MESSENGER_TRANSPORT_DSN: 'amqp://crypto-saas:crypto-saas@rabbit:5672/crypto-saas'
          DATABASE_URL: 'postgresql://crypto-saas:crypto-saas@postgres:5432/crypto-saas?serverVersion=16&charset=utf8'
          PROMETHEUS_URL: 'http://prometheus:9090'
          REDIS_DSN: 'redis://redis'
          ACCESS_TOKEN_TTL: 'P1Y'
          BREVO_API_KEY: ''
          OXA_PAY_API_KEY: 'sandbox'
          BACK_END_HOST: 'http://localhost'
          FRONT_END_HOST: 'http://localhost:3000'
          INTERNAL_SERVICE_TOKEN: 'internal-token'
      volumes:
        - ".:/srv/www"
        - ".docker/etc/php/php-dev.ini:/usr/local/etc/php/conf.d/99-php.ini"

      ports:
        - "81:80"

      networks:
        - crypto-saas
      restart: on-failure
      depends_on:
          postgres:
              condition: service_healthy
          redis:
              condition: service_started
#          - rabbit

    postgres:
        image: postgres:16-alpine
        restart: unless-stopped
        ports:
            - "5432:5432"
        networks:
            - crypto-saas
        environment:
            POSTGRES_DB: crypto-saas
            POSTGRES_USER: crypto-saas
            POSTGRES_PASSWORD: crypto-saas
        volumes:
            - pg-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U crypto-saas -d crypto-saas"]
            interval: 5s
            timeout: 3s
            retries: 10

    redis:
        image: redis:7-alpine
        networks:
            - crypto-saas
        volumes:
            - ./.docker/data/redis:/data:delegated
        ports:
            - "6378:6379"
        cap_add:
            - SYS_TIME
        restart: always

    # RabbitMQ
#    rabbit:
#        image: amashukov/rabbit3.6-management:latest
#        hostname: "crypto-saas"
#        networks:
#            - crypto-saas
#        environment:
#            RABBITMQ_DEFAULT_VHOST: crypto-saas
#            RABBITMQ_DEFAULT_USER: crypto-saas
#            RABBITMQ_DEFAULT_PASS: crypto-saas
#        cap_add:
#            - SYS_TIME
#        ports:
#            - 5674:5672
#            - 15674:15672
#        restart: always
#        volumes:
#            - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
#            - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/

volumes:
    pg-data:
        name: crypto-saas_pg_data
    s3data:
        name: crypto-saas_s3_data
    s3metadata:
        name: crypto-saas_s3_metadata

networks:
    crypto-saas:
        driver: bridge
