export const TRADE_LIMIT_SYMBOLS = [
    'NEOUSDT',
    'PERPUSDT',
    'ETHUSDT',
    'SOLUSDT',
    'BTCUSDT',
    'LTCUSDT',
    'XRPUSDT',
    'BNBUSDT',
    'TRXUSDT',
    'AVAXUSDT',
    'ADAUSDT',
    'DOGEUSDT',
    'BCHUSDT',
    'LINKUSDT',
    'MATICUSDT',
    'DOTUSDT',
    'UNIUSDT',
    'ETCUSDT',
    'XLMUSDT',
    'ATOMUSDT',
    'NEARUSDT',
    'ZECUSDT',
    'SHIBUSDT',
] as const;
