




parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true

    Bundles\UserContext\:
        resource: '../../../UserContext/'
        exclude:
            - '../../Entity/'
            - '../../Model/'
            - '../../Event/'
            - '../../UserContextBundle.php'

    _instanceof:
        Bundles\UserContext\Service\UserContextDecorator:
            tags: ['flagception.context_decorator']

    Bundles\UserContext\Service\EmailSender:
        arguments:
            $apiKey: '%env(BREVO_API_KEY)%'
