




parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true

    Bundles\OxaPayContext\:
        resource: '../../../OxaPayContext/'
        exclude:
            - '../../Entity/'
            - '../../Model/'
            - '../../OxaPayContextBundle.php'

    Bundles\OxaPayContext\Service\OxaPayClient:
        arguments:
            $apiKey: '%env(OXA_PAY_API_KEY)%'
            $backEndHost: '%env(BACK_END_HOST)%'
            $frontEndHost: '%env(FRONT_END_HOST)%'
