doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
#                JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
#                JSON_UNQUOTE: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonUnquote
#                JSON_VALUE: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mariadb\JsonValue
#                TIMESTAMPDIFF: Oro\ORM\Query\AST\Functions\Numeric\TimestampDiff
#                DATE_FORMAT: Oro\ORM\Query\AST\Functions\String\DateFormat
                DATEDIFF: DoctrineExtensions\Query\Mysql\DateDiff
                TIMEDIFF: DoctrineExtensions\Query\Mysql\TimeDiff
                TIME_TO_SEC: DoctrineExtensions\Query\Mysql\TimeToSec
                UNIX_TIMESTAMP: DoctrineExtensions\Query\Mysql\UnixTimestamp
                IF: DoctrineExtensions\Query\Mysql\IfElse
                CONCAT_WS: DoctrineExtensions\Query\Mysql\ConcatWs
                CAST: DoctrineExtensions\Query\Mysql\Cast
                DATE: DoctrineExtensions\Query\Mysql\Date
                GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
                HOUR: DoctrineExtensions\Query\Mysql\Hour
                WEEK: DoctrineExtensions\Query\Mysql\Week
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year
                IFNULL: DoctrineExtensions\Query\Mysql\IfNull
                REGEXP: DoctrineExtensions\Query\Mysql\Regexp
                FIELD: DoctrineExtensions\Query\Mysql\Field
#                first: App\DoctrineExtensions\Query\Mysql\First
#                ST_AsGeoJson: App\DoctrineExtensions\Query\Mysql\STAsGeoJson
            numeric_functions:
#                point: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Point
#                st_contains: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STContains
                pi: DoctrineExtensions\Query\Mysql\Pi
                degrees: DoctrineExtensions\Query\Mysql\Degrees
                radians: DoctrineExtensions\Query\Mysql\Radians
                round: DoctrineExtensions\Query\Mysql\Round
                cos: DoctrineExtensions\Query\Mysql\Cos
                sin: DoctrineExtensions\Query\Mysql\Sin
                acos: DoctrineExtensions\Query\Mysql\Acos
                atan: DoctrineExtensions\Query\Mysql\Atan
                least: DoctrineExtensions\Query\Mysql\Least
                power: DoctrineExtensions\Query\Mysql\Power
                floor: DoctrineExtensions\Query\Mysql\Floor
#                geo_distance: App\DoctrineExtensions\Query\Mysql\GeoDistance
                ceil: DoctrineExtensions\Query\Mysql\Ceil

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
