doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'




    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        controller_resolver:
            auto_mapping: false
        dql:
            string_functions:





                DATEDIFF: DoctrineExtensions\Query\Mysql\DateDiff
                TIMEDIFF: DoctrineExtensions\Query\Mysql\TimeDiff
                TIME_TO_SEC: DoctrineExtensions\Query\Mysql\TimeToSec
                UNIX_TIMESTAMP: DoctrineExtensions\Query\Mysql\UnixTimestamp
                IF: DoctrineExtensions\Query\Mysql\IfElse
                CONCAT_WS: DoctrineExtensions\Query\Mysql\ConcatWs
                CAST: DoctrineExtensions\Query\Mysql\Cast
                DATE: DoctrineExtensions\Query\Mysql\Date
                GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
                HOUR: DoctrineExtensions\Query\Mysql\Hour
                WEEK: DoctrineExtensions\Query\Mysql\Week
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year
                IFNULL: DoctrineExtensions\Query\Mysql\IfNull
                REGEXP: DoctrineExtensions\Query\Mysql\Regexp
                FIELD: DoctrineExtensions\Query\Mysql\Field


            numeric_functions:


                pi: DoctrineExtensions\Query\Mysql\Pi
                degrees: DoctrineExtensions\Query\Mysql\Degrees
                radians: DoctrineExtensions\Query\Mysql\Radians
                round: DoctrineExtensions\Query\Mysql\Round
                cos: DoctrineExtensions\Query\Mysql\Cos
                sin: DoctrineExtensions\Query\Mysql\Sin
                acos: DoctrineExtensions\Query\Mysql\Acos
                atan: DoctrineExtensions\Query\Mysql\Atan
                least: DoctrineExtensions\Query\Mysql\Least
                power: DoctrineExtensions\Query\Mysql\Power
                floor: DoctrineExtensions\Query\Mysql\Floor

                ceil: DoctrineExtensions\Query\Mysql\Ceil

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
