fos_rest:
    body_listener: true
    serializer:
        serialize_null: true
    format_listener:
        rules:
            - { path: '^/public', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/doc/(default|public|secure)$', priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
            - { path: '^/$', priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    param_fetcher_listener: true
    view:
        view_response_listener: true
        formats:
            json: true
            html: false
    exception:
        enabled: true
        serializer_error_renderer: true
        messages:
            Symfony\Component\HttpKernel\Exception\HttpException: true
            Symfony\Component\HttpKernel\Exception\BadRequestHttpException: true
            Symfony\Component\HttpKernel\Exception\NotFoundHttpException: true




    versioning: true
