league_oauth2_server:
    authorization_server:
        private_key: '%kernel.project_dir%/src/Resources/oauth/private.key'
        private_key_passphrase: null
        encryption_key: '%env(string:OAUTH2_ENCRYPTION_KEY)%'
        access_token_ttl: '%env(ACCESS_TOKEN_TTL)%'
        refresh_token_ttl: P6M

    resource_server:
        public_key: '%kernel.project_dir%/src/Resources/oauth/public.key'

    scopes:
        available: ['user']

    persistence:
        doctrine: ~
