security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            stateless: true
            security: false

    access_control:
        - { path: ^/, roles: PUBLIC_ACCESS }
