# CORS conditions
map $http_origin $cors {
	default 0;
	~^https?:\/\/(localhost|127\.0\.0\.1|0\.0\.0\.0|(.+\.)?autotrade\.(local|test|cloud))(:\d+)? 1;
}

server {
    listen 80 default_server;

    server_name "";
    root   /srv/www;

    proxy_buffer_size  1024k;
    proxy_buffers   4 2056k;
    proxy_busy_buffers_size   2056k;

    set $idx index.html;

    client_max_body_size 1024m;

    index $idx;

    gzip on;
    gzip_min_length 1000;
    gzip_comp_level 7;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml image/x-icon font/woff2 image/png;

    location ~ ^/(Dockerfile|composer\.json|composer\.lock|Makefile|readme\.md|md_ruleset\.xml|docker-compose\.yaml|config\.auto\.php|\.dockerignore|\.env\.dist|\.env|\.env\.template|\.gitignore|log\/|tests\/|ansible-cd\.yaml|utils) {
        return 403 'Access Denied.';
    }

    location / {
        try_files $uri $uri/ /$idx$is_args$args;
    }

    #access_log off;
    access_log /srv/www/log/nginx-access.log;
    error_log  /srv/www/log/nginx-error.log;
}
