create table trade_limit
(
    id           bigint generated by default as identity primary key,
    symbol       char(20)         not null,
    usdt_limit   double precision not null,
    min_price    double precision null,
    min_quantity double precision not null
);
