create table swap_pair
(
    id              bigint generated by default as identity primary key,
    source_symbol   char(20)         not null,
    symbol          char(20)         not null,
    base_asset      char(10)         not null,
    quote_asset     char(10)         not null,
    last_price      double precision not null,
    price_timestamp bigint           not null check (price_timestamp >= 0),
    min_notional    double precision not null,
    min_quantity    double precision not null,
    min_price       double precision not null
);
