create table bots
(
    id   bigint generated by default as identity primary key,
    uuid char(36) not null
);
insert into bots (uuid) values ('6c26e421-06fd-4c61-84d9-caf36b8966af');
alter table orders add column bot_id bigint default null;
update orders set bot_id = 1 where id > 0;
alter table orders alter column bot_id set not null;
alter table orders add constraint order_bot_id_fk foreign key (bot_id) references bots (id);
alter table trade_limit add column bot_id bigint default null;
update trade_limit set bot_id = 1 where id > 0;
alter table trade_limit alter column bot_id set not null;
alter table trade_limit add constraint trade_limit_bot_id_fk foreign key (bot_id) references bots (id);
