create type order_operation as enum ('sell', 'buy');
create type order_status as enum ('new', 'opened', 'closed', 'cancelled');

create table orders
(
    id          bigint generated by default as identity primary key,
    symbol      char(20)         not null,
    quantity    double precision not null,
    price       double precision not null,
    created_at  timestamptz      not null,
    sell_volume double precision not null,
    buy_volume  double precision not null,
    sma_value   double precision not null,
    operation   order_operation  not null,
    status      order_status     not null,
    external_id bigint           null,
    closed_by   bigint           null,
    constraint order_closed_by_fk
        foreign key (closed_by) references orders (id)
);
