create table swap_transition
(
    id          bigint generated by default as identity primary key,
    type        char(3)          not null,
    symbol      char(10)         not null,
    base_asset  char(10)         not null,
    quote_asset char(10)         not null,
    operation   char(4)          not null,
    quantity    double precision not null,
    price       double precision not null,
    level       double precision not null
);

create table swap_chain
(
    id         bigint generated by default as identity primary key,
    title      char(255)        not null,
    type       char(3)          not null,
    hash       char(32)         not null,
    swap_one   bigint           not null,
    swap_two   bigint           not null,
    swap_three bigint           not null,
    percent    double precision not null,
    timestamp  bigint           not null,
    constraint swap_transition_one_fk foreign key (swap_one) references swap_transition (id),
    constraint swap_transition_two_fk foreign key (swap_two) references swap_transition (id),
    constraint swap_transition_three_fk foreign key (swap_three) references swap_transition (id)
);
alter table swap_chain add constraint swap_chain_hash_uniq unique (hash);

alter table orders add column swap boolean not null default false;

create type swap_action_status as enum ('pending', 'process', 'canceled', 'success');

create table swap_action
(
    id                         bigint generated by default as identity primary key,
    order_id                   bigint              not null,
    bot_id                     bigint              not null,
    swap_chain_id              bigint              not null,
    asset                      char(10)            not null,
    status                     swap_action_status  not null,
    start_timestamp            bigint              not null,
    start_quantity             double precision    not null,
    end_timestamp              bigint              default null,
    end_quantity               double precision    default null,
    swap_one_external_id       bigint              default null,
    swap_one_external_status   char(20)            default null,
    swap_one_symbol            char(10)            not null,
    swap_one_price             double precision    not null,
    swap_one_timestamp         bigint              default null,
    swap_two_external_id       bigint              default null,
    swap_two_external_status   char(20)            default null,
    swap_two_symbol            char(10)            not null,
    swap_two_price             double precision    not null,
    swap_two_timestamp         bigint              default null,
    swap_three_external_id     bigint              default null,
    swap_three_external_status char(20)            default null,
    swap_three_symbol          char(10)            not null,
    swap_three_price           double precision    not null,
    swap_three_timestamp       bigint              default null,
    constraint swap_action_order_fk foreign key (order_id) references orders (id),
    constraint swap_action_swap_chain_fk foreign key (swap_chain_id) references swap_chain (id),
    constraint swap_action_bot_fk foreign key (bot_id) references bots (id)
);
