---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

  - name: Log into private registry and force re-authorization
    docker_login:
      registry: registry.gitlab.com
      username: gitlab-ci-token
      password: "{{ registry_password }}"
      reauthorize: yes

  - name: Pull latest project image
    docker_image:
      name: "{{ project_image }}"
      pull: yes
      force: yes

  - name: Re-create a project container
    docker_container:
      name: "{{ project_container }}"
      image: "{{ project_image }}"
      keep_volumes: yes
      recreate: yes
      restart_policy: unless-stopped
      state: started
      ports:
        - "127.0.0.1:8094:80"
      etc_hosts:
        "host.docker.internal" : "172.17.0.1"
      networks:
        - name: bridge
        - name: redis_net
#      volumes:
#        - "{{ project_container }}-storage:/srv/www/var/tdlib"
      memory: 2048M
      memory_swappiness: 1
      log_driver: json-file
      log_options:
          max-size: 10m
          max-file: 5

  - name: Execute migration command in docker container
    command: docker exec -it "{{ project_container }}" bash -c 'bin/console doctrine:migrations:migrate -n'

  - name: Execute var permissions command in docker container
    command: docker exec -it "{{ project_container }}" bash -c 'chown -R www-data /srv/www/var'
