# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Bundles\TgBotContext\:
        resource: '../../../TgBotContext/'
        exclude:
            - '../../Entity/'
            - '../../Model/'
            - '../../TgBotContextBundle.php'

    TgBotApi\BotApiBase\ApiClient:
        arguments:
            $requestFactory: '@Psr\Http\Message\RequestFactoryInterface'
            $streamFactory: '@Psr\Http\Message\StreamFactoryInterface'
            $client: '@Psr\Http\Client\ClientInterface'

    TgBotApi\BotApiBase\BotApiNormalizer: null

    TgBotApi\BotApiBase\ApiClientInterface: '@TgBotApi\BotApiBase\ApiClient'
    TgBotApi\BotApiBase\NormalizerInterface: '@TgBotApi\BotApiBase\BotApiNormalizer'

    TgBotApi\BotApiBase\BotApi:
        arguments:
            $botKey: '__BOT_TOKEN__'
            $apiClient: '@TgBotApi\BotApiBase\ApiClientInterface'
            $normalizer: '@TgBotApi\BotApiBase\NormalizerInterface'

    TgBotApi\BotApiBase\BotApiComplete:
        parent: TgBotApi\BotApiBase\BotApi

    TgBotApi\BotApiBase\BotApiInterface: '@TgBotApi\BotApiBase\BotApi'

    Bundles\TgBotContext\Service\AlertService:
        arguments:
            $env: '%kernel.environment%'
