doctrine:
  orm:
    mappings:
      UserContext:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/bundles/UserContext/Entity'
        prefix: 'Bundles\UserContextBundle\Entity'
        alias: UserContext
