name: Docker Image CI

on:
  push:
    branches: [main]
    paths:
      - 'server/**'
      - '.github/workflows/docker-image.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: amashukov
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Build the Docker image
        run: docker build server --file server/Dockerfile --tag amashukov/go-crypto-bot:latest
      - name: Publish the Docker image
        run: docker push amashukov/go-crypto-bot:latest
